# action.yml
name: 'AutoBOM'
description: 'Automatically export and render your hardware project'
inputs:
  repo-ref:
    description: "Reference to the repo to run AutoBOM on"
    required: true
runs:
  using: 'composite'
  steps:

    - name: Replace Github ENV Variables in Compose and Start Render Engines
      run: |
        envsubst < $GITHUB_ACTION_PATH/docker-compose.yaml.template > $GITHUB_ACTION_PATH/docker-compose.yml
        docker-compose -f $GITHUB_ACTION_PATH/docker-compose.yaml up -d
      shell: bash

    - name: Run AutoBOM
      run: |
          cd $GITHUB_WORKSPACE
          uv run --project $GITHUB_ACTION_PATH autobom
      shell: bash
      env:
        GITHUB_ACTION_PATH: $GITHUB_ACTION_PATH  # The action's path
        GITHUB_WORKSPACE: $GITHUB_WORKSPACE    # The user's repo workspace

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Autobom
        path: ./autobom

