# action.yml
name: 'AutoBOM'
description: 'Automatically export and render your hardware project'
inputs:
  repo-ref:
    description: "Reference to the repo to run AutoBOM on"
    required: true
runs:
  using: 'composite'
  steps:

    # - name: Replace Github ENV Variables in Compose
    #   run: |
    #     envsubst < $GITHUB_ACTION_PATH/docker-compose.yaml.template > $GITHUB_ACTION_PATH/docker-compose.yml
    #     ls
    #   shell: bash

    - name: Replace Github ENV Variables in Compose
      run: |
        set -x
        sed -i "s|\${GITHUB_ACTION_PATH}|$GITHUB_ACTION_PATH|g" ${{ github.action_path }}/docker-compose.yaml
        ls
      shell: bash

    - name: Start Render Engines
      run: |
        set -x
        docker compose -f ${{ github.action_path }}/docker-compose.yaml up -d
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # You can change this version based on your needs

    # Step 2: Install `uv` using pip
    - name: Install UV package manager
      run: |
        python -m pip install --upgrade pip
        pip install uv
      shell: bash

    - name: Run AutoBOM
      run: |
          set -x
          uv run --project $GITHUB_ACTION_PATH autobom
      shell: bash
      env:
        GITHUB_ACTION_PATH: $GITHUB_ACTION_PATH  # The action's path
        GITHUB_WORKSPACE: $GITHUB_WORKSPACE    # The user's repo workspace

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Autobom
        path: ./autobom

