services:
  freecad:
    image: ghcr.io/opulo-inc/autobom-freecad:${AUTOBOM_IMAGE_TAG:-latest}
    container_name: freecad
    volumes:
      - ${GITHUB_ACTION_PATH}/renderQueue:/renderQueue
    ports:
      - "9001:9001"

  kicad:
    image: ghcr.io/opulo-inc/autobom-kicad:${AUTOBOM_IMAGE_TAG:-latest}
    container_name: kicad
    volumes:
      - ${GITHUB_ACTION_PATH}/renderQueue:/renderQueue
    ports:
      - "9002:9002"
