services:
  # autobom:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: autobom
  #   volumes:
  #     - ./renderQueue:/renderQueue  # Shared folder for rendering
  #   
  #   depends_on:
  #     - freecad
  #     - kicad

  freecad:
    build:
      context: .
      dockerfile: render/Dockerfile-freecad-local
    container_name: freecad
    volumes:
      - ./renderQueue:/renderQueue
    ports:
      - "9001:9001"  # MCAD render server TCP port

  kicad:
    build:
        context: .
        dockerfile: render/Dockerfile-kicad
    container_name: kicad
    volumes:
      - ./renderQueue:/renderQueue
    ports:
      - "9002:9002"  # ECAD render server TCP port

