name: Run Autobom
on:
  workflow_dispatch:
  release:
    types: [ published ]
    
jobs:
  autobom:
    name: Autobom
    runs-on: ubuntu-latest
      
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Set Repo Path to ENV VAR
      run: export AUTOBOM_PATH=${GITHUB_WORKSPACE}

    - name: Run Autobom
      uses: opulo-inc/autobom@v1

    - name: Upload AutoBOM Artifact
      uses: