[project]
name = "autobom"
version = "0.2.0"
description = "Bill of Materials exporting and rendering for hardware projects"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [

]

[project.scripts]
autobom = "autobom:main"
export-freecad = "autobom.export_freecad:main"

[tool.uv]
package = true
