[project]
name = "autobom"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [

]

[project.scripts]
autobom = "autobom:main"

[tool.uv]
package = true